<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUJehZqk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUJehZqk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUJehZqk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUJehZqk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUJehZqk\App_KernelDevDebugContainer([
    'container.build_hash' => 'UJehZqk',
    'container.build_id' => '7292497f',
    'container.build_time' => 1607931097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUJehZqk');
